# ==============================================================================
# 不推荐自己维护此文件，如果确实有制定需求……
#
# 1. 将此文件复制到 ../config/ 下进行修改，不要直接修改此文件。
# 2. 每次更新时关注此文件的变更，在 ../config/ 下的同名文件中体现变更。
# 3. 切勿修改注释中的硬编码项（ XXX ）。
# 4. 全局唯一的项目保证 command.yml 和 command_master.yml 中唯一。
# ==============================================================================
# plugin:                    # 插件名称（禁止修改）
#   enable: boolean          # 是否加载插件
#   weights: number          # 权重越高，帮助信息里显示越靠前
#   regex:                   # 插件入口（正则、全局唯一匹配、忽略大小写）
#     - string
#   functions:
#     function:              # 功能代号（全局唯一、禁止修改）
#       weights: number      # 权重越高，帮助信息里显示越靠前
#       name: string         # 呈现给用户的功能名称
#       usage: string        # 呈现给用户的功能格式
#       description: string  # 呈现给用户的功能说明
#       entrance:            # 功能入口（ startsWith 、插件唯一匹配、忽略大小写）
#         - string
# ==============================================================================

aby:
  enable: true
  weights: 9699
  regex:
    - ^(上期)?深渊 *$
    - ^(上期)?深渊 +\d+.*$
    - ^(上期)?深渊 *\[CQ:at,qq=.*$
  functions:
    aby:
      weights: 9999
      name: 深渊
      usage: "[游戏内UID、@群友]"
      description:
      entrance:
        - ^深渊
    lastaby:
      weights: 9899
      name: 上期深渊
      usage: "[游戏内UID、@群友]"
      description:
      entrance:
        - ^上期深渊

artifacts:
  enable: true
  weights: 9299
  regex:
    - ^圣遗物 *$
    - ^圣遗物\s+\S+\s*$
    - ^(副本|秘境) *$
    - ^强化[\?\!？！]{0,} *$
  functions:
    artifacts:
      weights: 9999
      name: 圣遗物
      usage: "[副本编号]"
      description: 掉落一个圣遗物
      entrance:
        - ^圣遗物
    strengthen:
      weights: 9899
      name: 强化
      usage:
      description: 强化掉落的上一个圣遗物
      entrance:
        - ^强化
    dungeons:
      weights: 9799
      name: 副本
      usage:
      description: 查看所有副本编号
      entrance:
        - ^副本

card:
  enable: true
  weights: 9899
  regex:
    - ^米游社 *$
    - ^米游社 +\d+.*$
    - ^米游社 *\[CQ:at,qq=.*$
  functions:
    card:
      weights: 9999
      name: 米游社
      usage: "[米游社通行证ID、@群友]"
      description: 查询并更新角色信息
      entrance:
        - ^米游社

character:
  enable: true
  weights: 9599
  regex:
    - ^我的\s+\S+\s*$
    - ^((\[CQ:at,qq=.*?\])|(\d+))\s*的\s+\S+\s*$
  functions:
    character:
      type: command
      weights: 9999
      name: 我的
      usage: <角色名>
      description: 查询我的角色
      entrance:
        - ^我的
    others_character:
      type: command
      weights: 9899
      name: <游戏内UID、@群友>的
      usage: <角色名>
      description: 查询别人的角色
      entrance:
        - ^((\[CQ:at,qq=.*?\])|(\d+))$

gacha:
  enable: true
  weights: 9399
  regex:
    - ^(十连|wish) *$
    - ^(卡池|抽卡|祈愿) +(常驻|角色|武器) *$
    - ^(查看|取消)定轨 *$
    - ^定轨 +.+$
    - ^定轨 *$
  functions:
    gacha:
      type: command
      weights: 9999
      name: 十连
      usage:
      description:
      entrance:
        - ^十连
        - ^wish
    pool:
      type: option
      weights: 9899
      name: 卡池
      usage:
      description: 切换【十连】的卡池
      entrance:
        - 卡池
        - 抽卡
        - 祈愿
      options:
        200: 常驻
        301: 角色
        302: 武器
    select:
      weights: 9799
      name: 定轨
      usage: <武器名>
      description:
      entrance:
        - ^定轨
    select-what:
      weights: 9699
      name: 查看定轨
      usage:
      description:
      entrance:
        - ^查看定轨
    select-nothing:
      weights: 9599
      name: 取消定轨
      usage:
      description:
      entrance:
        - ^取消定轨

help:
  enable: true
  weights: 8699
  regex:
    - ^[Hh][Ee][Ll][Pp]$
    - ^帮助$
  functions:
    bot_help:
      weights: 9999
      name: help
      usage: 
      description: 查看本帮助
      entrance:
        - 帮助
        - H
        - h

tools:
  enable: true
  weights: 99
  regex:
    # 占卜功能自己写
    # - ^(求签|占卜)\s*$
    - ^roll\s*([+-]?\d+)?$
    - ([今明后早中晚上下][天晚个儿上午]{0,2}).{0,3}吃(什么|[啥嘛]) *[\?？]?|^今吃什$
    - ^吃(什么|[啥嘛]) *[\?？]?$
    - ^带(个)?话\s+.+$
    - ^管理\s*$
  functions:
    menu:
      weights: 9999
      name: 今天吃什么
      usage:
      description:
      entrance:
        - ([今明后早中晚上下][天晚个儿上午]{0,2}).{0,3}吃(什么|[啥嘛]) *[\?？]?|^今吃什$
        - ^吃(什么|[啥嘛]) *[\?？]?$
    # prophecy:
    #   weights: 9899
    #   name: 求签
    #   usage:
    #   description:
    #   entrance:
    #     - 求签
    #     - 占卜
    roll:
      weights: 9799
      name: roll
      usage: "[1-100]"
      description: 掷骰子
      entrance:
        - ^roll
    feedback:
      weights: 299
      name: 带话
      usage: <单行图文>
      description: 给主人带话
      entrance:
        - ^带话
        - ^带个话
    master:
      weights: 199
      name: 管理
      usage:
      description: 查看主人功能
      entrance:
        - ^管理
    # help:
    #   weights: 99
    #   name: help
    #   usage:
    #   description: 查看本帮助
    #   entrance:
    #     # - help

material:
  enable: true
  weights: 9099
  regex:
    - ^武器 *$
    - ^天赋 *$
    - ^周本 *$
  functions:
    weapon:
      weights: 9999
      name: 武器
      usage:
      description: 武器素材表
      entrance:
        - ^武器
    talent:
      weights: 9989
      name: 天赋
      usage:
      description: 天赋素材表
      entrance:
        - ^天赋
    weekly:
      weights: 9979
      name: 周本
      usage:
      description: 周本材料表
      entrance:
        - ^周本

music:
  enable: false
  weights: 8999
  regex:
    - ^点歌 +.+$
    - ^音乐源 +.+$
  functions:
    music:
      weights: 9999
      name: 点歌
      usage: <单行文本>
      description:
      entrance:
        - 点歌
    music_source:
      weights: 9899
      name: 音乐源
      usage: <QQ、163>
      description: 切换【点歌】的音乐源
      entrance:
        - 音乐源

overview:
  enable: true
  weights: 9499
  regex:
    - ^(角色|武器|信息)\s+\S+\s*$
  functions:
    info:
      weights: 9999
      name: 信息
      usage: <角色名、武器名>
      description: 查询角色或武器的游戏数据
      entrance:
        - ^信息
        - ^角色  # 历史原因
        - ^武器  # 历史原因

package:
  enable: true
  weights: 9799
  regex:
    - ^uid\s*$
    - ^uid\s+\d+\s*$
    - ^uid\s*\[CQ:at,qq=.*$
  functions:
    package:
      type: command
      weights: 9999
      name: uid
      usage: "[游戏内UID、@群友]"
      description: 查询并更新角色信息
      entrance:
        - ^uid

quote:
  enable: true
  weights: 8799
  regex:
    - ^[刻啊阿]晴语录 *$
  functions:
    quote:
      weights: 9999
      name: 阿晴语录
      usage:
      description:
      entrance:
        - ^[刻啊阿]晴语录

rating:
  enable: true
  weights: 9199
  regex:
    - ^评分(?![\u4E00-\u9FA5])[ \n]*.*$ # https://github.com/Arondight/Adachi-BOT/issues/54
  functions:
    rating:
      weights: 9999
      name: 评分
      usage: <背包中的圣遗物截图>
      description:
      entrance:
        - ^评分

save:
  enable: true
  weights: 9999
  regex:
    - ^(绑定|改绑)\s+\d+\s*$
  functions:
    save:
      type: command
      weights: 9999
      name: 绑定
      usage: <米游社通行证ID>
      description:
      entrance:
        - ^绑定
    change:
      type: command
      weights: 9899
      name: 改绑
      usage: <米游社通行证ID>
      description:
      entrance:
        - ^改绑

penguinlogistics:
  enable: true
  weights: 9099
  regex:
    - ^(查询)?掉落\s*.*$
  functions:
    penguinlogistics:
      weights: 9999
      name: 掉落查询
      usage: <物品名称>
      description: 查询企鹅物流中某物品的掉落情况
      entrance:
        - ^(查询)?掉落

chatbot:
  enable: true
  weights: 9099
  regex:
    - ^(?!.{0,5}[权限消息卡池回话广播列表系统无效]).*$
  functions:
    chatbot:
      weights: 9999
      name: 聊天功能
      usage: 
      description: 
      entrance:
        - ^(?!.{0,5}[权限消息卡池回话广播列表系统无效]).*$